### PR TITLE
Doubling stub with unit tests

### PR DESCRIPTION
**Pull request by RostislavIndyukovUofG**
Created an adapter design pattern for doubling input using a stub. Includes basic stub unit tests.

### CODE REVIEW

**Review by rosspow49 — COMMENTED** [review]
Good stub for file inputs that would help provide a consistent location for testing files that would not change between iterations. The getPlayList method in the main file seems to have little purpose as it only seems to call the getRawData function and return the output. The idea to have the directory for files as a variable is a good idea rather than having the value hardcoded each time it is used. This should be implemented into the PlaySound function for the sake of consistency.

**Review by Ross-Anderson94 — COMMENTED** [review]
All code is layed out in a very readable manner with all functions named very easily to understand. Only issue is an abstract method called ABC with calls from abc which is a little confusing naming convention. All indentation of the code is very nicely layed out and easy on the eyes to look over and understand which part is which.

**Review by christopherdmgunn — COMMENTED** [review]
Methods are clearly labeled with good variable names. 
Split into seperate files making it easier to read.
Renaming of variables and methods into more relevent names.
Only slightly confusing thing is an imported name abc which is an external library

**Review by DannyBgit — COMMENTED** [review]
Fantastic code, written clearly and readable. 
+Variables and method names clear and to the point
+Methods all do one thing and one thing only
-Changed python version from 3.9 to 3.10

**Review by FrazerScade — COMMENTED** [review]
The code is very well written and is very readable, methods are clearly distinct, appropriate spacing is used, meaningful variable names have been used and methods have been split up into separate files to keep different functions apart. The code version has also been updated to Python 3.10. The main class has been tidied up quite a bit and is now more readable than before. Could implement program finding song files rather than hardcoding them in.

**Pull request merged**
